#!/bin/bash

set -eu

# configure the splashscreen
mkdir -p $1/usr/share/plymouth/themes/macmind
chmod 755 $1/usr/share/plymouth/themes/macmind

mkdir -p $1/usr/share/plymouth/themes/blockchain
chmod 755 $1/usr/share/plymouth/themes/blockchain

rsync -a ${IGIMAGE}/plymouth/themes/macmind $1/usr/share/plymouth/themes/
rsync -a ${IGIMAGE}/plymouth/themes/blockchain $1/usr/share/plymouth/themes/

chmod 644 $1/usr/share/plymouth/themes/blockchain/*
chmod 644 $1/usr/share/plymouth/themes/macmind/*

# set the default theme to blockchain
chroot $1 plymouth-set-default-theme blockchain
